package io.github.projectmapk.jackson.module.kogera.zIntegration.deser.valueClass.parameterSize.nullablePrimitive

import com.fasterxml.jackson.annotation.JsonCreator
import io.github.projectmapk.jackson.module.kogera.assertReflectEquals
import io.github.projectmapk.jackson.module.kogera.defaultMapper
import io.github.projectmapk.jackson.module.kogera.readValue
import io.github.projectmapk.jackson.module.kogera.zIntegration.deser.valueClass.NullablePrimitive
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

/**
 * Up to argument size 32 there is one mask argument for the default argument,
 * 33 ~ 64 there are two, and 65 there are three, so each boundary value is tested.
 * Also, the maximum argument size that can be set in the constructor is 244, so that case is tested as well.
 */
class DeserializeByFactoryWithDefaultArgumentsTest {
    data class Dst32(
        val p00: NullablePrimitive?,
        val p01: NullablePrimitive?,
        val p02: NullablePrimitive?,
        val p03: NullablePrimitive?,
        val p04: NullablePrimitive?,
        val p05: NullablePrimitive?,
        val p06: NullablePrimitive?,
        val p07: NullablePrimitive?,
        val p08: NullablePrimitive?,
        val p09: NullablePrimitive?,
        val p10: NullablePrimitive?,
        val p11: NullablePrimitive?,
        val p12: NullablePrimitive?,
        val p13: NullablePrimitive?,
        val p14: NullablePrimitive?,
        val p15: NullablePrimitive?,
        val p16: NullablePrimitive?,
        val p17: NullablePrimitive?,
        val p18: NullablePrimitive?,
        val p19: NullablePrimitive?,
        val p20: NullablePrimitive?,
        val p21: NullablePrimitive?,
        val p22: NullablePrimitive?,
        val p23: NullablePrimitive?,
        val p24: NullablePrimitive?,
        val p25: NullablePrimitive?,
        val p26: NullablePrimitive?,
        val p27: NullablePrimitive?,
        val p28: NullablePrimitive?,
        val p29: NullablePrimitive?,
        val p30: NullablePrimitive?,
        val p31: NullablePrimitive?
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: NullablePrimitive? = NullablePrimitive(0),
                q01: NullablePrimitive? = NullablePrimitive(1),
                q02: NullablePrimitive? = NullablePrimitive(2),
                q03: NullablePrimitive? = NullablePrimitive(3),
                q04: NullablePrimitive? = NullablePrimitive(4),
                q05: NullablePrimitive? = NullablePrimitive(5),
                q06: NullablePrimitive? = NullablePrimitive(6),
                q07: NullablePrimitive? = NullablePrimitive(7),
                q08: NullablePrimitive? = NullablePrimitive(8),
                q09: NullablePrimitive? = NullablePrimitive(9),
                q10: NullablePrimitive? = NullablePrimitive(10),
                q11: NullablePrimitive? = NullablePrimitive(11),
                q12: NullablePrimitive? = NullablePrimitive(12),
                q13: NullablePrimitive? = NullablePrimitive(13),
                q14: NullablePrimitive? = NullablePrimitive(14),
                q15: NullablePrimitive? = NullablePrimitive(15),
                q16: NullablePrimitive? = NullablePrimitive(16),
                q17: NullablePrimitive? = NullablePrimitive(17),
                q18: NullablePrimitive? = NullablePrimitive(18),
                q19: NullablePrimitive? = NullablePrimitive(19),
                q20: NullablePrimitive? = NullablePrimitive(20),
                q21: NullablePrimitive? = NullablePrimitive(21),
                q22: NullablePrimitive? = NullablePrimitive(22),
                q23: NullablePrimitive? = NullablePrimitive(23),
                q24: NullablePrimitive? = NullablePrimitive(24),
                q25: NullablePrimitive? = NullablePrimitive(25),
                q26: NullablePrimitive? = NullablePrimitive(26),
                q27: NullablePrimitive? = NullablePrimitive(27),
                q28: NullablePrimitive? = NullablePrimitive(28),
                q29: NullablePrimitive? = NullablePrimitive(29),
                q30: NullablePrimitive? = NullablePrimitive(30),
                q31: NullablePrimitive? = NullablePrimitive(31)
            ) = Dst32(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31
            )
        }
    }

    @Test
    fun test32() {
        Assertions.assertEquals(Dst32.creator(), defaultMapper.readValue<Dst32>("{}"))
    }

    data class Dst33(
        val p00: NullablePrimitive?,
        val p01: NullablePrimitive?,
        val p02: NullablePrimitive?,
        val p03: NullablePrimitive?,
        val p04: NullablePrimitive?,
        val p05: NullablePrimitive?,
        val p06: NullablePrimitive?,
        val p07: NullablePrimitive?,
        val p08: NullablePrimitive?,
        val p09: NullablePrimitive?,
        val p10: NullablePrimitive?,
        val p11: NullablePrimitive?,
        val p12: NullablePrimitive?,
        val p13: NullablePrimitive?,
        val p14: NullablePrimitive?,
        val p15: NullablePrimitive?,
        val p16: NullablePrimitive?,
        val p17: NullablePrimitive?,
        val p18: NullablePrimitive?,
        val p19: NullablePrimitive?,
        val p20: NullablePrimitive?,
        val p21: NullablePrimitive?,
        val p22: NullablePrimitive?,
        val p23: NullablePrimitive?,
        val p24: NullablePrimitive?,
        val p25: NullablePrimitive?,
        val p26: NullablePrimitive?,
        val p27: NullablePrimitive?,
        val p28: NullablePrimitive?,
        val p29: NullablePrimitive?,
        val p30: NullablePrimitive?,
        val p31: NullablePrimitive?,
        val p32: NullablePrimitive?
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: NullablePrimitive? = NullablePrimitive(0),
                q01: NullablePrimitive? = NullablePrimitive(1),
                q02: NullablePrimitive? = NullablePrimitive(2),
                q03: NullablePrimitive? = NullablePrimitive(3),
                q04: NullablePrimitive? = NullablePrimitive(4),
                q05: NullablePrimitive? = NullablePrimitive(5),
                q06: NullablePrimitive? = NullablePrimitive(6),
                q07: NullablePrimitive? = NullablePrimitive(7),
                q08: NullablePrimitive? = NullablePrimitive(8),
                q09: NullablePrimitive? = NullablePrimitive(9),
                q10: NullablePrimitive? = NullablePrimitive(10),
                q11: NullablePrimitive? = NullablePrimitive(11),
                q12: NullablePrimitive? = NullablePrimitive(12),
                q13: NullablePrimitive? = NullablePrimitive(13),
                q14: NullablePrimitive? = NullablePrimitive(14),
                q15: NullablePrimitive? = NullablePrimitive(15),
                q16: NullablePrimitive? = NullablePrimitive(16),
                q17: NullablePrimitive? = NullablePrimitive(17),
                q18: NullablePrimitive? = NullablePrimitive(18),
                q19: NullablePrimitive? = NullablePrimitive(19),
                q20: NullablePrimitive? = NullablePrimitive(20),
                q21: NullablePrimitive? = NullablePrimitive(21),
                q22: NullablePrimitive? = NullablePrimitive(22),
                q23: NullablePrimitive? = NullablePrimitive(23),
                q24: NullablePrimitive? = NullablePrimitive(24),
                q25: NullablePrimitive? = NullablePrimitive(25),
                q26: NullablePrimitive? = NullablePrimitive(26),
                q27: NullablePrimitive? = NullablePrimitive(27),
                q28: NullablePrimitive? = NullablePrimitive(28),
                q29: NullablePrimitive? = NullablePrimitive(29),
                q30: NullablePrimitive? = NullablePrimitive(30),
                q31: NullablePrimitive? = NullablePrimitive(31),
                q32: NullablePrimitive? = NullablePrimitive(32)
            ) = Dst33(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31,
                q32
            )
        }
    }

    @Test
    fun test33() {
        Assertions.assertEquals(Dst33.creator(), defaultMapper.readValue<Dst33>("{}"))
    }

    data class Dst64(
        val p00: NullablePrimitive?,
        val p01: NullablePrimitive?,
        val p02: NullablePrimitive?,
        val p03: NullablePrimitive?,
        val p04: NullablePrimitive?,
        val p05: NullablePrimitive?,
        val p06: NullablePrimitive?,
        val p07: NullablePrimitive?,
        val p08: NullablePrimitive?,
        val p09: NullablePrimitive?,
        val p10: NullablePrimitive?,
        val p11: NullablePrimitive?,
        val p12: NullablePrimitive?,
        val p13: NullablePrimitive?,
        val p14: NullablePrimitive?,
        val p15: NullablePrimitive?,
        val p16: NullablePrimitive?,
        val p17: NullablePrimitive?,
        val p18: NullablePrimitive?,
        val p19: NullablePrimitive?,
        val p20: NullablePrimitive?,
        val p21: NullablePrimitive?,
        val p22: NullablePrimitive?,
        val p23: NullablePrimitive?,
        val p24: NullablePrimitive?,
        val p25: NullablePrimitive?,
        val p26: NullablePrimitive?,
        val p27: NullablePrimitive?,
        val p28: NullablePrimitive?,
        val p29: NullablePrimitive?,
        val p30: NullablePrimitive?,
        val p31: NullablePrimitive?,
        val p32: NullablePrimitive?,
        val p33: NullablePrimitive?,
        val p34: NullablePrimitive?,
        val p35: NullablePrimitive?,
        val p36: NullablePrimitive?,
        val p37: NullablePrimitive?,
        val p38: NullablePrimitive?,
        val p39: NullablePrimitive?,
        val p40: NullablePrimitive?,
        val p41: NullablePrimitive?,
        val p42: NullablePrimitive?,
        val p43: NullablePrimitive?,
        val p44: NullablePrimitive?,
        val p45: NullablePrimitive?,
        val p46: NullablePrimitive?,
        val p47: NullablePrimitive?,
        val p48: NullablePrimitive?,
        val p49: NullablePrimitive?,
        val p50: NullablePrimitive?,
        val p51: NullablePrimitive?,
        val p52: NullablePrimitive?,
        val p53: NullablePrimitive?,
        val p54: NullablePrimitive?,
        val p55: NullablePrimitive?,
        val p56: NullablePrimitive?,
        val p57: NullablePrimitive?,
        val p58: NullablePrimitive?,
        val p59: NullablePrimitive?,
        val p60: NullablePrimitive?,
        val p61: NullablePrimitive?,
        val p62: NullablePrimitive?,
        val p63: NullablePrimitive?
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: NullablePrimitive? = NullablePrimitive(0),
                q01: NullablePrimitive? = NullablePrimitive(1),
                q02: NullablePrimitive? = NullablePrimitive(2),
                q03: NullablePrimitive? = NullablePrimitive(3),
                q04: NullablePrimitive? = NullablePrimitive(4),
                q05: NullablePrimitive? = NullablePrimitive(5),
                q06: NullablePrimitive? = NullablePrimitive(6),
                q07: NullablePrimitive? = NullablePrimitive(7),
                q08: NullablePrimitive? = NullablePrimitive(8),
                q09: NullablePrimitive? = NullablePrimitive(9),
                q10: NullablePrimitive? = NullablePrimitive(10),
                q11: NullablePrimitive? = NullablePrimitive(11),
                q12: NullablePrimitive? = NullablePrimitive(12),
                q13: NullablePrimitive? = NullablePrimitive(13),
                q14: NullablePrimitive? = NullablePrimitive(14),
                q15: NullablePrimitive? = NullablePrimitive(15),
                q16: NullablePrimitive? = NullablePrimitive(16),
                q17: NullablePrimitive? = NullablePrimitive(17),
                q18: NullablePrimitive? = NullablePrimitive(18),
                q19: NullablePrimitive? = NullablePrimitive(19),
                q20: NullablePrimitive? = NullablePrimitive(20),
                q21: NullablePrimitive? = NullablePrimitive(21),
                q22: NullablePrimitive? = NullablePrimitive(22),
                q23: NullablePrimitive? = NullablePrimitive(23),
                q24: NullablePrimitive? = NullablePrimitive(24),
                q25: NullablePrimitive? = NullablePrimitive(25),
                q26: NullablePrimitive? = NullablePrimitive(26),
                q27: NullablePrimitive? = NullablePrimitive(27),
                q28: NullablePrimitive? = NullablePrimitive(28),
                q29: NullablePrimitive? = NullablePrimitive(29),
                q30: NullablePrimitive? = NullablePrimitive(30),
                q31: NullablePrimitive? = NullablePrimitive(31),
                q32: NullablePrimitive? = NullablePrimitive(32),
                q33: NullablePrimitive? = NullablePrimitive(33),
                q34: NullablePrimitive? = NullablePrimitive(34),
                q35: NullablePrimitive? = NullablePrimitive(35),
                q36: NullablePrimitive? = NullablePrimitive(36),
                q37: NullablePrimitive? = NullablePrimitive(37),
                q38: NullablePrimitive? = NullablePrimitive(38),
                q39: NullablePrimitive? = NullablePrimitive(39),
                q40: NullablePrimitive? = NullablePrimitive(40),
                q41: NullablePrimitive? = NullablePrimitive(41),
                q42: NullablePrimitive? = NullablePrimitive(42),
                q43: NullablePrimitive? = NullablePrimitive(43),
                q44: NullablePrimitive? = NullablePrimitive(44),
                q45: NullablePrimitive? = NullablePrimitive(45),
                q46: NullablePrimitive? = NullablePrimitive(46),
                q47: NullablePrimitive? = NullablePrimitive(47),
                q48: NullablePrimitive? = NullablePrimitive(48),
                q49: NullablePrimitive? = NullablePrimitive(49),
                q50: NullablePrimitive? = NullablePrimitive(50),
                q51: NullablePrimitive? = NullablePrimitive(51),
                q52: NullablePrimitive? = NullablePrimitive(52),
                q53: NullablePrimitive? = NullablePrimitive(53),
                q54: NullablePrimitive? = NullablePrimitive(54),
                q55: NullablePrimitive? = NullablePrimitive(55),
                q56: NullablePrimitive? = NullablePrimitive(56),
                q57: NullablePrimitive? = NullablePrimitive(57),
                q58: NullablePrimitive? = NullablePrimitive(58),
                q59: NullablePrimitive? = NullablePrimitive(59),
                q60: NullablePrimitive? = NullablePrimitive(60),
                q61: NullablePrimitive? = NullablePrimitive(61),
                q62: NullablePrimitive? = NullablePrimitive(62),
                q63: NullablePrimitive? = NullablePrimitive(63)
            ) = Dst64(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31,
                q32,
                q33,
                q34,
                q35,
                q36,
                q37,
                q38,
                q39,
                q40,
                q41,
                q42,
                q43,
                q44,
                q45,
                q46,
                q47,
                q48,
                q49,
                q50,
                q51,
                q52,
                q53,
                q54,
                q55,
                q56,
                q57,
                q58,
                q59,
                q60,
                q61,
                q62,
                q63
            )
        }
    }

    @Test
    fun test64() {
        Assertions.assertEquals(Dst64.creator(), defaultMapper.readValue<Dst64>("{}"))
    }

    data class Dst65(
        val p00: NullablePrimitive?,
        val p01: NullablePrimitive?,
        val p02: NullablePrimitive?,
        val p03: NullablePrimitive?,
        val p04: NullablePrimitive?,
        val p05: NullablePrimitive?,
        val p06: NullablePrimitive?,
        val p07: NullablePrimitive?,
        val p08: NullablePrimitive?,
        val p09: NullablePrimitive?,
        val p10: NullablePrimitive?,
        val p11: NullablePrimitive?,
        val p12: NullablePrimitive?,
        val p13: NullablePrimitive?,
        val p14: NullablePrimitive?,
        val p15: NullablePrimitive?,
        val p16: NullablePrimitive?,
        val p17: NullablePrimitive?,
        val p18: NullablePrimitive?,
        val p19: NullablePrimitive?,
        val p20: NullablePrimitive?,
        val p21: NullablePrimitive?,
        val p22: NullablePrimitive?,
        val p23: NullablePrimitive?,
        val p24: NullablePrimitive?,
        val p25: NullablePrimitive?,
        val p26: NullablePrimitive?,
        val p27: NullablePrimitive?,
        val p28: NullablePrimitive?,
        val p29: NullablePrimitive?,
        val p30: NullablePrimitive?,
        val p31: NullablePrimitive?,
        val p32: NullablePrimitive?,
        val p33: NullablePrimitive?,
        val p34: NullablePrimitive?,
        val p35: NullablePrimitive?,
        val p36: NullablePrimitive?,
        val p37: NullablePrimitive?,
        val p38: NullablePrimitive?,
        val p39: NullablePrimitive?,
        val p40: NullablePrimitive?,
        val p41: NullablePrimitive?,
        val p42: NullablePrimitive?,
        val p43: NullablePrimitive?,
        val p44: NullablePrimitive?,
        val p45: NullablePrimitive?,
        val p46: NullablePrimitive?,
        val p47: NullablePrimitive?,
        val p48: NullablePrimitive?,
        val p49: NullablePrimitive?,
        val p50: NullablePrimitive?,
        val p51: NullablePrimitive?,
        val p52: NullablePrimitive?,
        val p53: NullablePrimitive?,
        val p54: NullablePrimitive?,
        val p55: NullablePrimitive?,
        val p56: NullablePrimitive?,
        val p57: NullablePrimitive?,
        val p58: NullablePrimitive?,
        val p59: NullablePrimitive?,
        val p60: NullablePrimitive?,
        val p61: NullablePrimitive?,
        val p62: NullablePrimitive?,
        val p63: NullablePrimitive?,
        val p64: NullablePrimitive?
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: NullablePrimitive? = NullablePrimitive(0),
                q01: NullablePrimitive? = NullablePrimitive(1),
                q02: NullablePrimitive? = NullablePrimitive(2),
                q03: NullablePrimitive? = NullablePrimitive(3),
                q04: NullablePrimitive? = NullablePrimitive(4),
                q05: NullablePrimitive? = NullablePrimitive(5),
                q06: NullablePrimitive? = NullablePrimitive(6),
                q07: NullablePrimitive? = NullablePrimitive(7),
                q08: NullablePrimitive? = NullablePrimitive(8),
                q09: NullablePrimitive? = NullablePrimitive(9),
                q10: NullablePrimitive? = NullablePrimitive(10),
                q11: NullablePrimitive? = NullablePrimitive(11),
                q12: NullablePrimitive? = NullablePrimitive(12),
                q13: NullablePrimitive? = NullablePrimitive(13),
                q14: NullablePrimitive? = NullablePrimitive(14),
                q15: NullablePrimitive? = NullablePrimitive(15),
                q16: NullablePrimitive? = NullablePrimitive(16),
                q17: NullablePrimitive? = NullablePrimitive(17),
                q18: NullablePrimitive? = NullablePrimitive(18),
                q19: NullablePrimitive? = NullablePrimitive(19),
                q20: NullablePrimitive? = NullablePrimitive(20),
                q21: NullablePrimitive? = NullablePrimitive(21),
                q22: NullablePrimitive? = NullablePrimitive(22),
                q23: NullablePrimitive? = NullablePrimitive(23),
                q24: NullablePrimitive? = NullablePrimitive(24),
                q25: NullablePrimitive? = NullablePrimitive(25),
                q26: NullablePrimitive? = NullablePrimitive(26),
                q27: NullablePrimitive? = NullablePrimitive(27),
                q28: NullablePrimitive? = NullablePrimitive(28),
                q29: NullablePrimitive? = NullablePrimitive(29),
                q30: NullablePrimitive? = NullablePrimitive(30),
                q31: NullablePrimitive? = NullablePrimitive(31),
                q32: NullablePrimitive? = NullablePrimitive(32),
                q33: NullablePrimitive? = NullablePrimitive(33),
                q34: NullablePrimitive? = NullablePrimitive(34),
                q35: NullablePrimitive? = NullablePrimitive(35),
                q36: NullablePrimitive? = NullablePrimitive(36),
                q37: NullablePrimitive? = NullablePrimitive(37),
                q38: NullablePrimitive? = NullablePrimitive(38),
                q39: NullablePrimitive? = NullablePrimitive(39),
                q40: NullablePrimitive? = NullablePrimitive(40),
                q41: NullablePrimitive? = NullablePrimitive(41),
                q42: NullablePrimitive? = NullablePrimitive(42),
                q43: NullablePrimitive? = NullablePrimitive(43),
                q44: NullablePrimitive? = NullablePrimitive(44),
                q45: NullablePrimitive? = NullablePrimitive(45),
                q46: NullablePrimitive? = NullablePrimitive(46),
                q47: NullablePrimitive? = NullablePrimitive(47),
                q48: NullablePrimitive? = NullablePrimitive(48),
                q49: NullablePrimitive? = NullablePrimitive(49),
                q50: NullablePrimitive? = NullablePrimitive(50),
                q51: NullablePrimitive? = NullablePrimitive(51),
                q52: NullablePrimitive? = NullablePrimitive(52),
                q53: NullablePrimitive? = NullablePrimitive(53),
                q54: NullablePrimitive? = NullablePrimitive(54),
                q55: NullablePrimitive? = NullablePrimitive(55),
                q56: NullablePrimitive? = NullablePrimitive(56),
                q57: NullablePrimitive? = NullablePrimitive(57),
                q58: NullablePrimitive? = NullablePrimitive(58),
                q59: NullablePrimitive? = NullablePrimitive(59),
                q60: NullablePrimitive? = NullablePrimitive(60),
                q61: NullablePrimitive? = NullablePrimitive(61),
                q62: NullablePrimitive? = NullablePrimitive(62),
                q63: NullablePrimitive? = NullablePrimitive(63),
                q64: NullablePrimitive? = NullablePrimitive(64)
            ) = Dst65(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31,
                q32,
                q33,
                q34,
                q35,
                q36,
                q37,
                q38,
                q39,
                q40,
                q41,
                q42,
                q43,
                q44,
                q45,
                q46,
                q47,
                q48,
                q49,
                q50,
                q51,
                q52,
                q53,
                q54,
                q55,
                q56,
                q57,
                q58,
                q59,
                q60,
                q61,
                q62,
                q63,
                q64
            )
        }
    }

    @Test
    fun test65() {
        Assertions.assertEquals(Dst65.creator(), defaultMapper.readValue<Dst65>("{}"))
    }

    // It cannot be a data class because the generated method would exceed the argument size limit.
    class DstMax(
        val p000: NullablePrimitive?,
        val p001: NullablePrimitive?,
        val p002: NullablePrimitive?,
        val p003: NullablePrimitive?,
        val p004: NullablePrimitive?,
        val p005: NullablePrimitive?,
        val p006: NullablePrimitive?,
        val p007: NullablePrimitive?,
        val p008: NullablePrimitive?,
        val p009: NullablePrimitive?,
        val p010: NullablePrimitive?,
        val p011: NullablePrimitive?,
        val p012: NullablePrimitive?,
        val p013: NullablePrimitive?,
        val p014: NullablePrimitive?,
        val p015: NullablePrimitive?,
        val p016: NullablePrimitive?,
        val p017: NullablePrimitive?,
        val p018: NullablePrimitive?,
        val p019: NullablePrimitive?,
        val p020: NullablePrimitive?,
        val p021: NullablePrimitive?,
        val p022: NullablePrimitive?,
        val p023: NullablePrimitive?,
        val p024: NullablePrimitive?,
        val p025: NullablePrimitive?,
        val p026: NullablePrimitive?,
        val p027: NullablePrimitive?,
        val p028: NullablePrimitive?,
        val p029: NullablePrimitive?,
        val p030: NullablePrimitive?,
        val p031: NullablePrimitive?,
        val p032: NullablePrimitive?,
        val p033: NullablePrimitive?,
        val p034: NullablePrimitive?,
        val p035: NullablePrimitive?,
        val p036: NullablePrimitive?,
        val p037: NullablePrimitive?,
        val p038: NullablePrimitive?,
        val p039: NullablePrimitive?,
        val p040: NullablePrimitive?,
        val p041: NullablePrimitive?,
        val p042: NullablePrimitive?,
        val p043: NullablePrimitive?,
        val p044: NullablePrimitive?,
        val p045: NullablePrimitive?,
        val p046: NullablePrimitive?,
        val p047: NullablePrimitive?,
        val p048: NullablePrimitive?,
        val p049: NullablePrimitive?,
        val p050: NullablePrimitive?,
        val p051: NullablePrimitive?,
        val p052: NullablePrimitive?,
        val p053: NullablePrimitive?,
        val p054: NullablePrimitive?,
        val p055: NullablePrimitive?,
        val p056: NullablePrimitive?,
        val p057: NullablePrimitive?,
        val p058: NullablePrimitive?,
        val p059: NullablePrimitive?,
        val p060: NullablePrimitive?,
        val p061: NullablePrimitive?,
        val p062: NullablePrimitive?,
        val p063: NullablePrimitive?,
        val p064: NullablePrimitive?,
        val p065: NullablePrimitive?,
        val p066: NullablePrimitive?,
        val p067: NullablePrimitive?,
        val p068: NullablePrimitive?,
        val p069: NullablePrimitive?,
        val p070: NullablePrimitive?,
        val p071: NullablePrimitive?,
        val p072: NullablePrimitive?,
        val p073: NullablePrimitive?,
        val p074: NullablePrimitive?,
        val p075: NullablePrimitive?,
        val p076: NullablePrimitive?,
        val p077: NullablePrimitive?,
        val p078: NullablePrimitive?,
        val p079: NullablePrimitive?,
        val p080: NullablePrimitive?,
        val p081: NullablePrimitive?,
        val p082: NullablePrimitive?,
        val p083: NullablePrimitive?,
        val p084: NullablePrimitive?,
        val p085: NullablePrimitive?,
        val p086: NullablePrimitive?,
        val p087: NullablePrimitive?,
        val p088: NullablePrimitive?,
        val p089: NullablePrimitive?,
        val p090: NullablePrimitive?,
        val p091: NullablePrimitive?,
        val p092: NullablePrimitive?,
        val p093: NullablePrimitive?,
        val p094: NullablePrimitive?,
        val p095: NullablePrimitive?,
        val p096: NullablePrimitive?,
        val p097: NullablePrimitive?,
        val p098: NullablePrimitive?,
        val p099: NullablePrimitive?,
        val p100: NullablePrimitive?,
        val p101: NullablePrimitive?,
        val p102: NullablePrimitive?,
        val p103: NullablePrimitive?,
        val p104: NullablePrimitive?,
        val p105: NullablePrimitive?,
        val p106: NullablePrimitive?,
        val p107: NullablePrimitive?,
        val p108: NullablePrimitive?,
        val p109: NullablePrimitive?,
        val p110: NullablePrimitive?,
        val p111: NullablePrimitive?,
        val p112: NullablePrimitive?,
        val p113: NullablePrimitive?,
        val p114: NullablePrimitive?,
        val p115: NullablePrimitive?,
        val p116: NullablePrimitive?,
        val p117: NullablePrimitive?,
        val p118: NullablePrimitive?,
        val p119: NullablePrimitive?,
        val p120: NullablePrimitive?,
        val p121: NullablePrimitive?,
        val p122: NullablePrimitive?,
        val p123: NullablePrimitive?,
        val p124: NullablePrimitive?,
        val p125: NullablePrimitive?,
        val p126: NullablePrimitive?,
        val p127: NullablePrimitive?,
        val p128: NullablePrimitive?,
        val p129: NullablePrimitive?,
        val p130: NullablePrimitive?,
        val p131: NullablePrimitive?,
        val p132: NullablePrimitive?,
        val p133: NullablePrimitive?,
        val p134: NullablePrimitive?,
        val p135: NullablePrimitive?,
        val p136: NullablePrimitive?,
        val p137: NullablePrimitive?,
        val p138: NullablePrimitive?,
        val p139: NullablePrimitive?,
        val p140: NullablePrimitive?,
        val p141: NullablePrimitive?,
        val p142: NullablePrimitive?,
        val p143: NullablePrimitive?,
        val p144: NullablePrimitive?,
        val p145: NullablePrimitive?,
        val p146: NullablePrimitive?,
        val p147: NullablePrimitive?,
        val p148: NullablePrimitive?,
        val p149: NullablePrimitive?,
        val p150: NullablePrimitive?,
        val p151: NullablePrimitive?,
        val p152: NullablePrimitive?,
        val p153: NullablePrimitive?,
        val p154: NullablePrimitive?,
        val p155: NullablePrimitive?,
        val p156: NullablePrimitive?,
        val p157: NullablePrimitive?,
        val p158: NullablePrimitive?,
        val p159: NullablePrimitive?,
        val p160: NullablePrimitive?,
        val p161: NullablePrimitive?,
        val p162: NullablePrimitive?,
        val p163: NullablePrimitive?,
        val p164: NullablePrimitive?,
        val p165: NullablePrimitive?,
        val p166: NullablePrimitive?,
        val p167: NullablePrimitive?,
        val p168: NullablePrimitive?,
        val p169: NullablePrimitive?,
        val p170: NullablePrimitive?,
        val p171: NullablePrimitive?,
        val p172: NullablePrimitive?,
        val p173: NullablePrimitive?,
        val p174: NullablePrimitive?,
        val p175: NullablePrimitive?,
        val p176: NullablePrimitive?,
        val p177: NullablePrimitive?,
        val p178: NullablePrimitive?,
        val p179: NullablePrimitive?,
        val p180: NullablePrimitive?,
        val p181: NullablePrimitive?,
        val p182: NullablePrimitive?,
        val p183: NullablePrimitive?,
        val p184: NullablePrimitive?,
        val p185: NullablePrimitive?,
        val p186: NullablePrimitive?,
        val p187: NullablePrimitive?,
        val p188: NullablePrimitive?,
        val p189: NullablePrimitive?,
        val p190: NullablePrimitive?,
        val p191: NullablePrimitive?,
        val p192: NullablePrimitive?,
        val p193: NullablePrimitive?,
        val p194: NullablePrimitive?,
        val p195: NullablePrimitive?,
        val p196: NullablePrimitive?,
        val p197: NullablePrimitive?,
        val p198: NullablePrimitive?,
        val p199: NullablePrimitive?,
        val p200: NullablePrimitive?,
        val p201: NullablePrimitive?,
        val p202: NullablePrimitive?,
        val p203: NullablePrimitive?,
        val p204: NullablePrimitive?,
        val p205: NullablePrimitive?,
        val p206: NullablePrimitive?,
        val p207: NullablePrimitive?,
        val p208: NullablePrimitive?,
        val p209: NullablePrimitive?,
        val p210: NullablePrimitive?,
        val p211: NullablePrimitive?,
        val p212: NullablePrimitive?,
        val p213: NullablePrimitive?,
        val p214: NullablePrimitive?,
        val p215: NullablePrimitive?,
        val p216: NullablePrimitive?,
        val p217: NullablePrimitive?,
        val p218: NullablePrimitive?,
        val p219: NullablePrimitive?,
        val p220: NullablePrimitive?,
        val p221: NullablePrimitive?,
        val p222: NullablePrimitive?,
        val p223: NullablePrimitive?,
        val p224: NullablePrimitive?,
        val p225: NullablePrimitive?,
        val p226: NullablePrimitive?,
        val p227: NullablePrimitive?,
        val p228: NullablePrimitive?,
        val p229: NullablePrimitive?,
        val p230: NullablePrimitive?,
        val p231: NullablePrimitive?,
        val p232: NullablePrimitive?,
        val p233: NullablePrimitive?,
        val p234: NullablePrimitive?,
        val p235: NullablePrimitive?,
        val p236: NullablePrimitive?,
        val p237: NullablePrimitive?,
        val p238: NullablePrimitive?,
        val p239: NullablePrimitive?,
        val p240: NullablePrimitive?,
        val p241: NullablePrimitive?,
        val p242: NullablePrimitive?,
        val p243: NullablePrimitive?
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q000: NullablePrimitive? = NullablePrimitive(0),
                q001: NullablePrimitive? = NullablePrimitive(1),
                q002: NullablePrimitive? = NullablePrimitive(2),
                q003: NullablePrimitive? = NullablePrimitive(3),
                q004: NullablePrimitive? = NullablePrimitive(4),
                q005: NullablePrimitive? = NullablePrimitive(5),
                q006: NullablePrimitive? = NullablePrimitive(6),
                q007: NullablePrimitive? = NullablePrimitive(7),
                q008: NullablePrimitive? = NullablePrimitive(8),
                q009: NullablePrimitive? = NullablePrimitive(9),
                q010: NullablePrimitive? = NullablePrimitive(10),
                q011: NullablePrimitive? = NullablePrimitive(11),
                q012: NullablePrimitive? = NullablePrimitive(12),
                q013: NullablePrimitive? = NullablePrimitive(13),
                q014: NullablePrimitive? = NullablePrimitive(14),
                q015: NullablePrimitive? = NullablePrimitive(15),
                q016: NullablePrimitive? = NullablePrimitive(16),
                q017: NullablePrimitive? = NullablePrimitive(17),
                q018: NullablePrimitive? = NullablePrimitive(18),
                q019: NullablePrimitive? = NullablePrimitive(19),
                q020: NullablePrimitive? = NullablePrimitive(20),
                q021: NullablePrimitive? = NullablePrimitive(21),
                q022: NullablePrimitive? = NullablePrimitive(22),
                q023: NullablePrimitive? = NullablePrimitive(23),
                q024: NullablePrimitive? = NullablePrimitive(24),
                q025: NullablePrimitive? = NullablePrimitive(25),
                q026: NullablePrimitive? = NullablePrimitive(26),
                q027: NullablePrimitive? = NullablePrimitive(27),
                q028: NullablePrimitive? = NullablePrimitive(28),
                q029: NullablePrimitive? = NullablePrimitive(29),
                q030: NullablePrimitive? = NullablePrimitive(30),
                q031: NullablePrimitive? = NullablePrimitive(31),
                q032: NullablePrimitive? = NullablePrimitive(32),
                q033: NullablePrimitive? = NullablePrimitive(33),
                q034: NullablePrimitive? = NullablePrimitive(34),
                q035: NullablePrimitive? = NullablePrimitive(35),
                q036: NullablePrimitive? = NullablePrimitive(36),
                q037: NullablePrimitive? = NullablePrimitive(37),
                q038: NullablePrimitive? = NullablePrimitive(38),
                q039: NullablePrimitive? = NullablePrimitive(39),
                q040: NullablePrimitive? = NullablePrimitive(40),
                q041: NullablePrimitive? = NullablePrimitive(41),
                q042: NullablePrimitive? = NullablePrimitive(42),
                q043: NullablePrimitive? = NullablePrimitive(43),
                q044: NullablePrimitive? = NullablePrimitive(44),
                q045: NullablePrimitive? = NullablePrimitive(45),
                q046: NullablePrimitive? = NullablePrimitive(46),
                q047: NullablePrimitive? = NullablePrimitive(47),
                q048: NullablePrimitive? = NullablePrimitive(48),
                q049: NullablePrimitive? = NullablePrimitive(49),
                q050: NullablePrimitive? = NullablePrimitive(50),
                q051: NullablePrimitive? = NullablePrimitive(51),
                q052: NullablePrimitive? = NullablePrimitive(52),
                q053: NullablePrimitive? = NullablePrimitive(53),
                q054: NullablePrimitive? = NullablePrimitive(54),
                q055: NullablePrimitive? = NullablePrimitive(55),
                q056: NullablePrimitive? = NullablePrimitive(56),
                q057: NullablePrimitive? = NullablePrimitive(57),
                q058: NullablePrimitive? = NullablePrimitive(58),
                q059: NullablePrimitive? = NullablePrimitive(59),
                q060: NullablePrimitive? = NullablePrimitive(60),
                q061: NullablePrimitive? = NullablePrimitive(61),
                q062: NullablePrimitive? = NullablePrimitive(62),
                q063: NullablePrimitive? = NullablePrimitive(63),
                q064: NullablePrimitive? = NullablePrimitive(64),
                q065: NullablePrimitive? = NullablePrimitive(65),
                q066: NullablePrimitive? = NullablePrimitive(66),
                q067: NullablePrimitive? = NullablePrimitive(67),
                q068: NullablePrimitive? = NullablePrimitive(68),
                q069: NullablePrimitive? = NullablePrimitive(69),
                q070: NullablePrimitive? = NullablePrimitive(70),
                q071: NullablePrimitive? = NullablePrimitive(71),
                q072: NullablePrimitive? = NullablePrimitive(72),
                q073: NullablePrimitive? = NullablePrimitive(73),
                q074: NullablePrimitive? = NullablePrimitive(74),
                q075: NullablePrimitive? = NullablePrimitive(75),
                q076: NullablePrimitive? = NullablePrimitive(76),
                q077: NullablePrimitive? = NullablePrimitive(77),
                q078: NullablePrimitive? = NullablePrimitive(78),
                q079: NullablePrimitive? = NullablePrimitive(79),
                q080: NullablePrimitive? = NullablePrimitive(80),
                q081: NullablePrimitive? = NullablePrimitive(81),
                q082: NullablePrimitive? = NullablePrimitive(82),
                q083: NullablePrimitive? = NullablePrimitive(83),
                q084: NullablePrimitive? = NullablePrimitive(84),
                q085: NullablePrimitive? = NullablePrimitive(85),
                q086: NullablePrimitive? = NullablePrimitive(86),
                q087: NullablePrimitive? = NullablePrimitive(87),
                q088: NullablePrimitive? = NullablePrimitive(88),
                q089: NullablePrimitive? = NullablePrimitive(89),
                q090: NullablePrimitive? = NullablePrimitive(90),
                q091: NullablePrimitive? = NullablePrimitive(91),
                q092: NullablePrimitive? = NullablePrimitive(92),
                q093: NullablePrimitive? = NullablePrimitive(93),
                q094: NullablePrimitive? = NullablePrimitive(94),
                q095: NullablePrimitive? = NullablePrimitive(95),
                q096: NullablePrimitive? = NullablePrimitive(96),
                q097: NullablePrimitive? = NullablePrimitive(97),
                q098: NullablePrimitive? = NullablePrimitive(98),
                q099: NullablePrimitive? = NullablePrimitive(99),
                q100: NullablePrimitive? = NullablePrimitive(100),
                q101: NullablePrimitive? = NullablePrimitive(101),
                q102: NullablePrimitive? = NullablePrimitive(102),
                q103: NullablePrimitive? = NullablePrimitive(103),
                q104: NullablePrimitive? = NullablePrimitive(104),
                q105: NullablePrimitive? = NullablePrimitive(105),
                q106: NullablePrimitive? = NullablePrimitive(106),
                q107: NullablePrimitive? = NullablePrimitive(107),
                q108: NullablePrimitive? = NullablePrimitive(108),
                q109: NullablePrimitive? = NullablePrimitive(109),
                q110: NullablePrimitive? = NullablePrimitive(110),
                q111: NullablePrimitive? = NullablePrimitive(111),
                q112: NullablePrimitive? = NullablePrimitive(112),
                q113: NullablePrimitive? = NullablePrimitive(113),
                q114: NullablePrimitive? = NullablePrimitive(114),
                q115: NullablePrimitive? = NullablePrimitive(115),
                q116: NullablePrimitive? = NullablePrimitive(116),
                q117: NullablePrimitive? = NullablePrimitive(117),
                q118: NullablePrimitive? = NullablePrimitive(118),
                q119: NullablePrimitive? = NullablePrimitive(119),
                q120: NullablePrimitive? = NullablePrimitive(120),
                q121: NullablePrimitive? = NullablePrimitive(121),
                q122: NullablePrimitive? = NullablePrimitive(122),
                q123: NullablePrimitive? = NullablePrimitive(123),
                q124: NullablePrimitive? = NullablePrimitive(124),
                q125: NullablePrimitive? = NullablePrimitive(125),
                q126: NullablePrimitive? = NullablePrimitive(126),
                q127: NullablePrimitive? = NullablePrimitive(127),
                q128: NullablePrimitive? = NullablePrimitive(128),
                q129: NullablePrimitive? = NullablePrimitive(129),
                q130: NullablePrimitive? = NullablePrimitive(130),
                q131: NullablePrimitive? = NullablePrimitive(131),
                q132: NullablePrimitive? = NullablePrimitive(132),
                q133: NullablePrimitive? = NullablePrimitive(133),
                q134: NullablePrimitive? = NullablePrimitive(134),
                q135: NullablePrimitive? = NullablePrimitive(135),
                q136: NullablePrimitive? = NullablePrimitive(136),
                q137: NullablePrimitive? = NullablePrimitive(137),
                q138: NullablePrimitive? = NullablePrimitive(138),
                q139: NullablePrimitive? = NullablePrimitive(139),
                q140: NullablePrimitive? = NullablePrimitive(140),
                q141: NullablePrimitive? = NullablePrimitive(141),
                q142: NullablePrimitive? = NullablePrimitive(142),
                q143: NullablePrimitive? = NullablePrimitive(143),
                q144: NullablePrimitive? = NullablePrimitive(144),
                q145: NullablePrimitive? = NullablePrimitive(145),
                q146: NullablePrimitive? = NullablePrimitive(146),
                q147: NullablePrimitive? = NullablePrimitive(147),
                q148: NullablePrimitive? = NullablePrimitive(148),
                q149: NullablePrimitive? = NullablePrimitive(149),
                q150: NullablePrimitive? = NullablePrimitive(150),
                q151: NullablePrimitive? = NullablePrimitive(151),
                q152: NullablePrimitive? = NullablePrimitive(152),
                q153: NullablePrimitive? = NullablePrimitive(153),
                q154: NullablePrimitive? = NullablePrimitive(154),
                q155: NullablePrimitive? = NullablePrimitive(155),
                q156: NullablePrimitive? = NullablePrimitive(156),
                q157: NullablePrimitive? = NullablePrimitive(157),
                q158: NullablePrimitive? = NullablePrimitive(158),
                q159: NullablePrimitive? = NullablePrimitive(159),
                q160: NullablePrimitive? = NullablePrimitive(160),
                q161: NullablePrimitive? = NullablePrimitive(161),
                q162: NullablePrimitive? = NullablePrimitive(162),
                q163: NullablePrimitive? = NullablePrimitive(163),
                q164: NullablePrimitive? = NullablePrimitive(164),
                q165: NullablePrimitive? = NullablePrimitive(165),
                q166: NullablePrimitive? = NullablePrimitive(166),
                q167: NullablePrimitive? = NullablePrimitive(167),
                q168: NullablePrimitive? = NullablePrimitive(168),
                q169: NullablePrimitive? = NullablePrimitive(169),
                q170: NullablePrimitive? = NullablePrimitive(170),
                q171: NullablePrimitive? = NullablePrimitive(171),
                q172: NullablePrimitive? = NullablePrimitive(172),
                q173: NullablePrimitive? = NullablePrimitive(173),
                q174: NullablePrimitive? = NullablePrimitive(174),
                q175: NullablePrimitive? = NullablePrimitive(175),
                q176: NullablePrimitive? = NullablePrimitive(176),
                q177: NullablePrimitive? = NullablePrimitive(177),
                q178: NullablePrimitive? = NullablePrimitive(178),
                q179: NullablePrimitive? = NullablePrimitive(179),
                q180: NullablePrimitive? = NullablePrimitive(180),
                q181: NullablePrimitive? = NullablePrimitive(181),
                q182: NullablePrimitive? = NullablePrimitive(182),
                q183: NullablePrimitive? = NullablePrimitive(183),
                q184: NullablePrimitive? = NullablePrimitive(184),
                q185: NullablePrimitive? = NullablePrimitive(185),
                q186: NullablePrimitive? = NullablePrimitive(186),
                q187: NullablePrimitive? = NullablePrimitive(187),
                q188: NullablePrimitive? = NullablePrimitive(188),
                q189: NullablePrimitive? = NullablePrimitive(189),
                q190: NullablePrimitive? = NullablePrimitive(190),
                q191: NullablePrimitive? = NullablePrimitive(191),
                q192: NullablePrimitive? = NullablePrimitive(192),
                q193: NullablePrimitive? = NullablePrimitive(193),
                q194: NullablePrimitive? = NullablePrimitive(194),
                q195: NullablePrimitive? = NullablePrimitive(195),
                q196: NullablePrimitive? = NullablePrimitive(196),
                q197: NullablePrimitive? = NullablePrimitive(197),
                q198: NullablePrimitive? = NullablePrimitive(198),
                q199: NullablePrimitive? = NullablePrimitive(199),
                q200: NullablePrimitive? = NullablePrimitive(200),
                q201: NullablePrimitive? = NullablePrimitive(201),
                q202: NullablePrimitive? = NullablePrimitive(202),
                q203: NullablePrimitive? = NullablePrimitive(203),
                q204: NullablePrimitive? = NullablePrimitive(204),
                q205: NullablePrimitive? = NullablePrimitive(205),
                q206: NullablePrimitive? = NullablePrimitive(206),
                q207: NullablePrimitive? = NullablePrimitive(207),
                q208: NullablePrimitive? = NullablePrimitive(208),
                q209: NullablePrimitive? = NullablePrimitive(209),
                q210: NullablePrimitive? = NullablePrimitive(210),
                q211: NullablePrimitive? = NullablePrimitive(211),
                q212: NullablePrimitive? = NullablePrimitive(212),
                q213: NullablePrimitive? = NullablePrimitive(213),
                q214: NullablePrimitive? = NullablePrimitive(214),
                q215: NullablePrimitive? = NullablePrimitive(215),
                q216: NullablePrimitive? = NullablePrimitive(216),
                q217: NullablePrimitive? = NullablePrimitive(217),
                q218: NullablePrimitive? = NullablePrimitive(218),
                q219: NullablePrimitive? = NullablePrimitive(219),
                q220: NullablePrimitive? = NullablePrimitive(220),
                q221: NullablePrimitive? = NullablePrimitive(221),
                q222: NullablePrimitive? = NullablePrimitive(222),
                q223: NullablePrimitive? = NullablePrimitive(223),
                q224: NullablePrimitive? = NullablePrimitive(224),
                q225: NullablePrimitive? = NullablePrimitive(225),
                q226: NullablePrimitive? = NullablePrimitive(226),
                q227: NullablePrimitive? = NullablePrimitive(227),
                q228: NullablePrimitive? = NullablePrimitive(228),
                q229: NullablePrimitive? = NullablePrimitive(229),
                q230: NullablePrimitive? = NullablePrimitive(230),
                q231: NullablePrimitive? = NullablePrimitive(231),
                q232: NullablePrimitive? = NullablePrimitive(232),
                q233: NullablePrimitive? = NullablePrimitive(233),
                q234: NullablePrimitive? = NullablePrimitive(234),
                q235: NullablePrimitive? = NullablePrimitive(235),
                q236: NullablePrimitive? = NullablePrimitive(236),
                q237: NullablePrimitive? = NullablePrimitive(237),
                q238: NullablePrimitive? = NullablePrimitive(238),
                q239: NullablePrimitive? = NullablePrimitive(239),
                q240: NullablePrimitive? = NullablePrimitive(240),
                q241: NullablePrimitive? = NullablePrimitive(241),
                q242: NullablePrimitive? = NullablePrimitive(242),
                q243: NullablePrimitive? = NullablePrimitive(243)
            ) = DstMax(
                q000,
                q001,
                q002,
                q003,
                q004,
                q005,
                q006,
                q007,
                q008,
                q009,
                q010,
                q011,
                q012,
                q013,
                q014,
                q015,
                q016,
                q017,
                q018,
                q019,
                q020,
                q021,
                q022,
                q023,
                q024,
                q025,
                q026,
                q027,
                q028,
                q029,
                q030,
                q031,
                q032,
                q033,
                q034,
                q035,
                q036,
                q037,
                q038,
                q039,
                q040,
                q041,
                q042,
                q043,
                q044,
                q045,
                q046,
                q047,
                q048,
                q049,
                q050,
                q051,
                q052,
                q053,
                q054,
                q055,
                q056,
                q057,
                q058,
                q059,
                q060,
                q061,
                q062,
                q063,
                q064,
                q065,
                q066,
                q067,
                q068,
                q069,
                q070,
                q071,
                q072,
                q073,
                q074,
                q075,
                q076,
                q077,
                q078,
                q079,
                q080,
                q081,
                q082,
                q083,
                q084,
                q085,
                q086,
                q087,
                q088,
                q089,
                q090,
                q091,
                q092,
                q093,
                q094,
                q095,
                q096,
                q097,
                q098,
                q099,
                q100,
                q101,
                q102,
                q103,
                q104,
                q105,
                q106,
                q107,
                q108,
                q109,
                q110,
                q111,
                q112,
                q113,
                q114,
                q115,
                q116,
                q117,
                q118,
                q119,
                q120,
                q121,
                q122,
                q123,
                q124,
                q125,
                q126,
                q127,
                q128,
                q129,
                q130,
                q131,
                q132,
                q133,
                q134,
                q135,
                q136,
                q137,
                q138,
                q139,
                q140,
                q141,
                q142,
                q143,
                q144,
                q145,
                q146,
                q147,
                q148,
                q149,
                q150,
                q151,
                q152,
                q153,
                q154,
                q155,
                q156,
                q157,
                q158,
                q159,
                q160,
                q161,
                q162,
                q163,
                q164,
                q165,
                q166,
                q167,
                q168,
                q169,
                q170,
                q171,
                q172,
                q173,
                q174,
                q175,
                q176,
                q177,
                q178,
                q179,
                q180,
                q181,
                q182,
                q183,
                q184,
                q185,
                q186,
                q187,
                q188,
                q189,
                q190,
                q191,
                q192,
                q193,
                q194,
                q195,
                q196,
                q197,
                q198,
                q199,
                q200,
                q201,
                q202,
                q203,
                q204,
                q205,
                q206,
                q207,
                q208,
                q209,
                q210,
                q211,
                q212,
                q213,
                q214,
                q215,
                q216,
                q217,
                q218,
                q219,
                q220,
                q221,
                q222,
                q223,
                q224,
                q225,
                q226,
                q227,
                q228,
                q229,
                q230,
                q231,
                q232,
                q233,
                q234,
                q235,
                q236,
                q237,
                q238,
                q239,
                q240,
                q241,
                q242,
                q243
            )
        }
    }

    @Test
    fun testMax() {
        assertReflectEquals(DstMax.creator(), defaultMapper.readValue<DstMax>("{}"))
    }
}
